rtmp: yes
rtmpAddress: :1935

hls: yes  
hlsAddress: :8888

metrics: yes
metricsAddress: :9998

# Disable authentication completely for streaming
authMethod: internal
authInternalUsers:
  - user: any
    pass: ""
    ips: ['127.0.0.1', '::1', '172.18.0.0/16', '0.0.0.0/0']
    permissions:
      - action: api
      - action: metrics
      - action: publish
        path: "~^.*"
      - action: read
        path: "~^.*"

paths:
  all: {}
