# MediaMTX configuration
# Use only spaces, no tabs

logLevel: info
logDestinations: [stdout]
logFile: ""

# RTMP server
rtmpAddress: :1935
rtmpEncryption: "no"
rtmpServerKey: ""
rtmpServerCert: ""

# HLS server  
hlsAddress: :8888
hlsEncryption: false
hlsServerKey: ""
hlsServerCert: ""
hlsAlwaysRemux: false
hlsVariant: lowLatency
hlsSegmentCount: 3
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsDirectory: ""

# WebRTC server
webrtcAddress: :8889
webrtcEncryption: false
webrtcServerKey: ""
webrtcServerCert: ""
webrtcAllowOrigin: "*"
webrtcTrustedProxies: []
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: :8189

# API server
api: true
apiAddress: :9997

# Metrics
metrics: true
metricsAddress: :9998

# Paths
paths:
  all:
    source: publisher
    sourceProtocol: automatic
    sourceAnyPortEnable: false
    sourceFingerprint: ""
    sourceOnDemand: false
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s
    sourceRedirect: ""
    disablePublisherOverride: false
    fallback: ""
    srtReadPassphrase: ""
    srtPublishPassphrase: ""
    record: false
